ipHeader:
  headers:
    - X-Forwarded-For
    - X-Real-IP
    - RemoteAddr

rateLimits:
  localhost:8080:
    destination: "https://kamdoautoskoly.cz"
    requests: 10
    perSecond: 60

  users:
    destination: "api/users"
    requests: 50
    perSecond: 1

  admin:
    destination: "api/admin"
    requests: 1000
    perSecond: 1