ipHeader:
  headers:
    - X-Forwarded-For
    - X-Real-IP
    - RemoteAddr

# Global Google Auth configuration
googleAuth:
  enabled: true
  clientId: "xxxxx"
  clientSecret: "GOCSPX-xxxxx"
  # Redirect URL bude vždy na auth doméně
  redirectUrl: "https://auth.mojedomena.com/auth/callback"
  # Domény, které jsou chráněné autentizací
  protectedDomains:
    - "localhost:8080"
    - "dev-cods-admin.jale.cz"

rateLimits:
  "localhost:8080":
    destination: "http://localhost:8881"
    requests: -1
    perSecond: -1
    # black list for domain
    ipBlackList:
      - "1.1.1.1"
    cacheMaxTtlSeconds: 3600
    allowedEmails:
      - "jakubloffelmann@gmail.com"
  dev-cods-admin.jale.cz:
    destination: "http://dev-cods-admin.app:2000"
    requests: 50
    perSecond: 1
    allowedEmails: []  # Empty list means no Google login for this domain

# global black list
ipBlackList:
  - "2.2.2.2"