ipHeader:
  headers:
    - X-Forwarded-For
    - X-Real-IP
    - RemoteAddr

rateLimits:
  "localhost:8080":
    destination: "http://localhost:8881"
    requests: -1
    perSecond: -1
    # black list for domain
    ipBlackList:
      - "1.1.1.1"
    cacheMaxTtlSeconds: 3600
    googleAuth:
      enabled: true
      clientId: "xxxxx"
      clientSecret: "GOCSPX-xxxxx"
      redirectUrl: "http://localhost:8080/auth/callback"
      allowedEmails:
        - "jakubloffelmann@gmail.com"
  dev-cods-admin.jale.cz:
    destination: "http://dev-cods-admin.app:2000"
    requests: 50
    perSecond: 1

# global black list
ipBlackList:
  - "2.2.2.2"