ipHeader:
  headers:
    - X-Forwarded-For
    - X-Real-IP
    - RemoteAddr

# Global Google Auth configuration
googleAuth:
  enabled: true
  clientId: "xxxxx"
  clientSecret: "GOCSPX-xxxxx"
  # Auth domain for login processing
  authDomain: "auth.jale.cz"
  # Redirect URL will always be on the auth domain
  redirectUrl: "https://auth.jale.cz/auth/callback"
  # Domains that are protected by authentication
  protectedDomains:
    - "localhost:8080"
    - "dev-cods-admin.jale.cz"
    - "auto.cz"
  # Domains that share cookies
  sharedDomains:
    - "jale.cz"
    - "auto.cz"
    - "localhost:8080"

rateLimits:
  "localhost:8080":
    destination: "http://localhost:8881"
    requests: -1
    perSecond: -1
    ipBlackList:
      - "1.1.1.1"
    allowedEmails: []
  dev-cods-admin.jale.cz:
    destination: "http://dev-cods-admin.app:2000"
    requests: 50
    perSecond: 1
    allowedEmails: []
  auto.cz:
    destination: "http://auto.app:2000"
    requests: 50
    perSecond: 1
    allowedEmails:
      - "jakubloffelmann@gmail.com"

# global black list
ipBlackList:
  - "2.2.2.2"